/* Project Lighthouse's reusable room registry. Rooms are permanent; projects move through them. */
window.lighthouseRooms = [
  { id: 'office', number: '01', name: 'Career Office', eyebrow: 'Professional foundation', description: 'Current resume, career goals, certifications, and the professional record behind the work.', activeLabel: 'On the desk now', active: 'Game design and QA case studies that show practical systems thinking.', archiveLabel: 'Filing cabinet', archive: ['Previous roles and responsibilities', 'Past resumes and certifications', 'Professional notes and references'], action: { label: 'Open career office', href: '#office' } },
  { id: 'studio', number: '02', name: 'Music Studio', eyebrow: 'KidAither lives here', description: 'Current writing and releases live on the console. Finished work has a deliberate place on the shelf.', activeLabel: 'At the mixing desk', active: 'Songwriting, visual direction, release planning, and creative identity work.', archiveLabel: 'Record shelf', archive: ['Released songs and projects', 'Lyric journals', 'Artwork and visual references'], action: { label: 'Visit the studio', href: '#studio' } },
  { id: 'lab', number: '03', name: 'Game Development Lab', eyebrow: 'Systems in motion', description: 'The primary workstation for game design, QA thinking, prototypes, and player-experience work.', activeLabel: 'On the main monitor', active: 'Gameplay systems, test cases, prototypes, and design documentation.', archiveLabel: 'Storage shelf', archive: ['Completed prototypes', 'Build notes and QA reports', 'Mechanic and level-design studies'], action: { label: 'See current work', href: '#work' } },
  { id: 'workshop', number: '04', name: 'Concept Workshop', eyebrow: 'Ideas with structure', description: 'A working room for experiments, worldbuilding, AI exploration, and concepts still becoming themselves.', activeLabel: 'On the workbench', active: 'Creative systems and new directions worth testing before they become projects.', archiveLabel: 'Blueprint drawer', archive: ['Finished concept documents', 'Worldbuilding references', 'Experiment logs and lessons'], action: { label: 'Explore current concepts', href: '#work' } },
  { id: 'library', number: '05', name: 'Research Library', eyebrow: 'Useful knowledge, kept', description: 'Writing, research, source material, and notes that keep new work grounded in what has already been learned.', activeLabel: 'Open on the reading table', active: 'Research notes, useful references, and writing in progress.', archiveLabel: 'Reference shelves', archive: ['Research collections', 'Completed writing', 'Learning notes and source lists'], action: { label: 'View the library', href: '#rooms' } },
  { id: 'observatory', number: '06', name: 'Observatory', eyebrow: 'The next horizon', description: 'The quiet place for long-range goals, reflection, and deciding what deserves the next season of attention.', activeLabel: 'In view tonight', active: 'Career direction, long-term creative goals, and the work worth growing toward.', archiveLabel: 'Field journal', archive: ['Milestones and reflections', 'Completed goal cycles', 'Future-facing notes'], action: { label: 'Return to the welcome room', href: '#home' } }
];
